In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
data_train= pd.read_csv("trainA.csv", header=None)
data_test= pd.read_csv("testA.csv", header=None)
data_train.head(5)

0                                                  1
0  2  WASHINGTON — The White House moved on Thursday...
1  2  Text size\n\nJust a year ago, American health-...
2  2  As communities around the world face an unprec...
3  2  CHOLOMA, Honduras — More than 400 people died ...
4  2  TORONTO, Oct. 11, 2019 /CNW/ - While Premier D...

In [ ]:
data_train[0].unique()

array([2, 1, 0])

In [ ]:
data_test[0].unique()

array([2, 1, 0])

In [ ]:
df_bert = pd.DataFrame({
 'id':range(len(data_train)),
 'label':data_train[0],
 'alpha':['a']*data_train.shape[0],
 'text': data_train[1].replace(r'\n', ' ', regex=True)
})

In [ ]:
df_bert.head()

id  label alpha                                               text
0   0      2     a  WASHINGTON — The White House moved on Thursday...
1   1      2     a  Text size  Just a year ago, American health-in...
2   2      2     a  As communities around the world face an unprec...
3   3      2     a  CHOLOMA, Honduras — More than 400 people died ...
4   4      2     a  TORONTO, Oct. 11, 2019 /CNW/ - While Premier D...

In [ ]:
df_bert_train, df_bert_dev = train_test_split(df_bert, test_size=0.01)

In [ ]:
df_bert_test = pd.DataFrame({
 'id':range(len(data_test)),
 'text': data_test[1].replace(r'\n', ' ', regex=True)
})
df_bert_test.tail()

id                                               text
651  651  An immunotherapy drug has been hailed as a pot...
652  652  Philadelphia, PA, August 14, 2017 - Stanford U...
653  653  LOS ANGELES - The supplement Aged Garlic Extra...
654  654  Worcester, Mass. - When the standard malaria m...
655  655  WHAT: A new study shows that the drug fenofibr...

In [ ]:
df_bert_train.to_csv("train.tsv", sep='\t', index=False, header=False)
df_bert_dev.to_csv('dev.tsv', sep='\t', index=False, header=False)
df_bert_test.to_csv('test.tsv', sep='\t', index=False, header=True)

1.   Bert models are fine-tuned using the train, test and dev tsv files.
2.   The program outputs a test_results file, which is used to calculate the acccuracy or f1 score.

In [ ]:
import  csv
label_results=[]
pd.DataFrame()
with open('test_results.tsv') as file:
    rd = csv.reader(file, delimiter="\t")
    for row in rd:
      data_1=[float(i) for i in row]
      label_results.append(data_1.index(max(data_1)))
df_results=pd.DataFrame()
df_results=pd.DataFrame(label_results)
df_results[0]

0      2
1      2
2      2
3      2
4      2
      ..
651    1
652    1
653    1
654    1
655    1
Name: 0, Length: 656, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data_test[0], df_results[0])

array([[  1, 178,   0],
       [  1, 178,   0],
       [  0,   0, 298]])

In [ ]:
from sklearn import metrics
print("Accuracy",metrics.accuracy_score(data_test[0], df_results[0]))
print("F1-Score",metrics.f1_score(data_test[0], df_results[0],average='weighted'))

Accuracy 0.7271341463414634
F1-Score 0.6388539343388993
